Add configuration file and keep launcher setting persisted
IntelOrca/OpenLauncher pull request #11
Opened 2022-09-23 11:43 UTC by beam41

This is pretty basic but actual data persistence on Avalonia required ReactiveUI which this repo doesn't have, also it would be really overkill.

Newer .net has System.Text.Json built-in so I have to update target framework and save config in json format.

Fix: #4

2022-09-23 11:57 UTC, beam41 commented
btw, if there are any others way to save and reinitialize setting. You can tell me to implement it because I don't know much about Avalonia and this solution is my only idea.

2022-09-24 14:22 UTC, IntelOrca requested changes
Looks good, just need to be a bit more defensive. I have also provided some other suggestions.

2022-09-24 14:22 UTC, IntelOrca commented on src/IntelOrca.OpenLauncher.Core/IntelOrca.OpenLauncher.Core.csproj
> +    <TargetFramework>net6.0</TargetFramework>
In order to keep it as .NET standard 2.1, you will need to add a package reference to `System.Text.Json` version 6.0.0. You can see this already being done with `System.Collections.Immutable`. When you build openlauncher which is net6.0, it will not actually distribute those assemblies because it knows they are part of .NET 6.

You might need to update the language version due to some of the syntax you have used.

2022-09-24 14:22 UTC, IntelOrca commented on src/IntelOrca.OpenLauncher.Core/ConfigService.cs
> +        public int SelectingGame { get; set; } = 0;
You can remove these initialises because bool and int already default to false and 0. This then means you can ditch the constructor.

2022-09-24 14:22 UTC, IntelOrca commented on src/IntelOrca.OpenLauncher.Core/ConfigService.cs
> +            File.WriteAllText(ConfigFilePath, configJson);
This should be wrapped in a try catch, you don't want the launcher to crash if it can't save for any reason.

2022-09-24 14:22 UTC, IntelOrca commented on src/IntelOrca.OpenLauncher.Core/ConfigService.cs
> +            }
This should also be wrapped in a try catch, if it can't load the config file you still want the launcher to work.

2022-09-24 14:22 UTC, IntelOrca commented on src/IntelOrca.OpenLauncher.Core/ConfigService.cs
> +using System.Threading.Tasks;
Remove unused usings

2022-09-24 18:09 UTC, beam41 commented on src/IntelOrca.OpenLauncher.Core/IntelOrca.OpenLauncher.Core.csproj
> +    <TargetFramework>net6.0</TargetFramework>
Oh, I didn't know that before. I had work on asp but not app, so thank for new knowledge.

2022-09-26 08:14 UTC, IntelOrca commented on src/IntelOrca.OpenLauncher.Core/IntelOrca.OpenLauncher.Core.csproj
> +    <PackageReference Include="System.Text.Json" Version="6.0.6" />
```suggestion
    <PackageReference Include="System.Text.Json" Version="6.0.0" />
```

2022-09-27 11:10 UTC, IntelOrca approved these changes

2022-09-27 11:35 UTC, merged